services:
  web:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
