# Generated by Django 4.2.23 on 2025-06-30 10:35

from django.db import migrations


def create_statuses(apps, schema_editor):
    Status = apps.get_model('books', 'Status')
    Status.objects.bulk_create([
        Status(name='未読'),
        Status(name='読書中'),
        Status(name='読了'),
        Status(name='気になる'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_status'),
    ]

    operations = [
        migrations.RunPython(create_statuses),
    ]
